### ISSUE TITLE
Unable to make zipcpu

### ISSUE THREAD

**Issue by rohitkverma1998** [ZipCPU/zipcpu#12]
(base) rajjo@rajjo-darlz:~/zipcpu$ make
Building rtl for Verilator
make[1]: Nothing to be done for 'all'.
Building toolchain
make --no-print-directory --directory=build-gas
make[5]: Nothing to be done for 'all'.
make[4]: Nothing to be done for 'all'.
true "AR_FLAGS=rc" "CC_FOR_BUILD=gcc" "CFLAGS=-g -O2" "CXXFLAGS=-g -O2" "CFLAGS_FOR_BUILD=-g -O2" "CFLAGS_FOR_TARGET=-g -O2" "INSTALL=/usr/bin/install -c" "INSTALL_DATA=/usr/bin/install -c -m 644" "INSTALL_PROGRAM=/usr/bin/install -c" "INSTALL_SCRIPT=/usr/bin/install -c" "LDFLAGS=-static-libstdc++ -static-libgcc " "LIBCFLAGS=-g -O2" "LIBCFLAGS_FOR_TARGET=-g -O2" "MAKE=make" "MAKEINFO=makeinfo --split-size=5000000 --split-size=5000000 " "PICFLAG=" "PICFLAG_FOR_TARGET=" "SHELL=/bin/bash" "EXPECT=expect" "RUNTEST=runtest" "RUNTESTFLAGS=" "exec_prefix=/home/rajjo/zipcpu/sw/install/cross-tools" "infodir=/home/rajjo/zipcpu/sw/install/cross-tools/share/info" "libdir=/home/rajjo/zipcpu/sw/install/cross-tools/lib" "prefix=/home/rajjo/zipcpu/sw/install/cross-tools" "tooldir=/home/rajjo/zipcpu/sw/install/cross-tools/zip" "AR=ar" "AS=as" "CC=gcc" "CXX=g++" "LD=ld" "LIBCFLAGS=-g -O2" "NM=nm" "PICFLAG=" "RANLIB=ranlib" "DESTDIR=" DO=all multi-do # make
Making info in doc
Making info in po
make[5]: Nothing to be done for 'info'.
make[5]: Nothing to be done for 'info-am'.
make  all-recursive
Making all in doc
make[6]: Nothing to be done for 'all'.
Making all in po
make[6]: Nothing to be done for 'all'.
make  all-recursive
Making all in .
Making all in po
make[6]: Nothing to be done for 'all'.
make  all-recursive
Making all in doc
make[6]: Nothing to be done for 'all'.
Making all in po
make[6]: Nothing to be done for 'all'.
Making info in doc
make[5]: Nothing to be done for 'info'.
Making info in po
make[5]: Nothing to be done for 'info'.
make[5]: Nothing to be done for 'info-am'.
make  all-recursive
Making all in doc
make[6]: Nothing to be done for 'all'.
Making all in po
make[6]: Nothing to be done for 'all'.
make[4]: Nothing to be done for 'all'.
make  all-recursive
Making all in po
make[6]: Nothing to be done for 'all'.
make[3]: Nothing to be done for 'all-target'.
Binutils package build complete
make --no-print-directory --directory=build-gas install
/bin/bash ../binutils-2.27-zip/mkinstalldirs /home/rajjo/zipcpu/sw/install/cross-tools /home/rajjo/zipcpu/sw/install/cross-tools
make  install-recursive
Making install in doc
 /bin/mkdir -p '/home/rajjo/zipcpu/sw/install/cross-tools/share/info'
 /usr/bin/install -c -m 644 ./bfd.info '/home/rajjo/zipcpu/sw/install/cross-tools/share/info'
 install-info --info-dir='/home/rajjo/zipcpu/sw/install/cross-tools/share/info' '/home/rajjo/zipcpu/sw/install/cross-tools/share/info/bfd.info'
Making install in po
make[6]: Nothing to be done for 'install'.
make[7]: Nothing to be done for 'install-exec-am'.
Making install in .
make[6]: Nothing to be done for 'install-exec-am'.
Making install in po
make[5]: Nothing to be done for 'install'.
make  install-recursive
Making install in doc
make[7]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/home/rajjo/zipcpu/sw/install/cross-tools/share/info'
 /usr/bin/install -c -m 644 ../../../binutils-2.27-zip/binutils/doc/binutils.info '/home/rajjo/zipcpu/sw/install/cross-tools/share/info'
 install-info --info-dir='/home/rajjo/zipcpu/sw/install/cross-tools/share/info' '/home/rajjo/zipcpu/sw/install/cross-tools/share/info/binutils.info'
 /bin/mkdir -p '/home/rajjo/zipcpu/sw/install/cross-tools/share/man/man1'
 /usr/bin/install -c -m 644 '../../../binutils-2.27-zip/binutils/doc/addr2line.1' '/home/rajjo/zipcpu/sw/install/cross-tools/share/man/man1/zip-addr2line.1'
 /usr/bin/install -c -m 644 '../../../binutils-2.27-zip/binutils/doc/ar.1' '/home/rajjo/zipcpu/sw/install/cross-tools/share/man/man1/zip-ar.1'
 /usr/bin/install -c -m 644 '../../../binutils-2.27-zip/binutils/doc/dlltool.1' '/home/rajjo/zipcpu/sw/install/cross-tools/share/man/man1/zip-dlltool.1'
 /usr/bin/install -c -m 644 '../../../binutils-2.27-zip/binutils/doc/nlmconv.1' '/home/rajjo/zipcpu/sw/install/cross-tools/share/man/man1/zip-nlmconv.1'
 /usr/bin/install -c -m 644 '../../../binutils-2.27-zip/binutils/doc/nm.1' '/home/rajjo/zipcpu/sw/install/cross-tools/share/man/man1/zip-nm.1'
 /usr/bin/install -c -m 644 '../../../binutils-2.27-zip/binutils/doc/objcopy.1' '/home/rajjo/zipcpu/sw/install/cross-tools/share/man/man1/zip-objcopy.1'
 /usr/bin/install -c -m 644 '../../../binutils-2.27-zip/binutils/doc/objdump.1' '/home/rajjo/zipcpu/sw/install/cross-tools/share/man/man1/zip-objdump.1'
 /usr/bin/install -c -m 644 '../../../binutils-2.27-zip/binutils/doc/ranlib.1' '/home/rajjo/zipcpu/sw/install/cross-tools/share/man/man1/zip-ranlib.1'
 /usr/bin/install -c -m 644 '../../../binutils-2.27-zip/binutils/doc/readelf.1' '/home/rajjo/zipcpu/sw/install/cross-tools/share/man/man1/zip-readelf.1'
 /usr/bin/install -c -m 644 '../../../binutils-2.27-zip/binutils/doc/size.1' '/home/rajjo/zipcpu/sw/install/cross-tools/share/man/man1/zip-size.1'
 /usr/bin/install -c -m 644 '../../../binutils-2.27-zip/binutils/doc/strings.1' '/home/rajjo/zipcpu/sw/install/cross-tools/share/man/man1/zip-strings.1'
 /usr/bin/install -c -m 644 '../../../binutils-2.27-zip/binutils/doc/strip.1' '/home/rajjo/zipcpu/sw/install/cross-tools/share/man/man1/zip-strip.1'
 /usr/bin/install -c -m 644 '../../../binutils-2.27-zip/binutils/doc/elfedit.1' '/home/rajjo/zipcpu/sw/install/cross-tools/share/man/man1/zip-elfedit.1'
 /usr/bin/install -c -m 644 '../../../binutils-2.27-zip/binutils/doc/windres.1' '/home/rajjo/zipcpu/sw/install/cross-tools/share/man/man1/zip-windres.1'
 /usr/bin/install -c -m 644 '../../../binutils-2.27-zip/binutils/doc/windmc.1' '/home/rajjo/zipcpu/sw/install/cross-tools/share/man/man1/zip-windmc.1'
 /usr/bin/install -c -m 644 'c++filt.1' '/home/rajjo/zipcpu/sw/install/cross-tools/share/man/man1/zip-c++filt.1'
Making install in po
make[6]: Nothing to be done for 'install'.
 /bin/mkdir -p '/home/rajjo/zipcpu/sw/install/cross-tools/bin'
  /bin/bash ./libtool   --mode=install /usr/bin/install -c size '/home/rajjo/zipcpu/sw/install/cross-tools/bin/./zip-size'
libtool: install: /usr/bin/install -c size /home/rajjo/zipcpu/sw/install/cross-tools/bin/./zip-size
  /bin/bash ./libtool   --mode=install /usr/bin/install -c objdump '/home/rajjo/zipcpu/sw/install/cross-tools/bin/./zip-objdump'
libtool: install: /usr/bin/install -c objdump /home/rajjo/zipcpu/sw/install/cross-tools/bin/./zip-objdump
  /bin/bash ./libtool   --mode=install /usr/bin/install -c ar '/home/rajjo/zipcpu/sw/install/cross-tools/bin/./zip-ar'
libtool: install: /usr/bin/install -c ar /home/rajjo/zipcpu/sw/install/cross-tools/bin/./zip-ar
  /bin/bash ./libtool   --mode=install /usr/bin/install -c strings '/home/rajjo/zipcpu/sw/install/cross-tools/bin/./zip-strings'
libtool: install: /usr/bin/install -c strings /home/rajjo/zipcpu/sw/install/cross-tools/bin/./zip-strings
  /bin/bash ./libtool   --mode=install /usr/bin/install -c ranlib '/home/rajjo/zipcpu/sw/install/cross-tools/bin/./zip-ranlib'
libtool: install: /usr/bin/install -c ranlib /home/rajjo/zipcpu/sw/install/cross-tools/bin/./zip-ranlib
  /bin/bash ./libtool   --mode=install /usr/bin/install -c objcopy '/home/rajjo/zipcpu/sw/install/cross-tools/bin/./zip-objcopy'
libtool: install: /usr/bin/install -c objcopy /home/rajjo/zipcpu/sw/install/cross-tools/bin/./zip-objcopy
  /bin/bash ./libtool   --mode=install /usr/bin/install -c addr2line '/home/rajjo/zipcpu/sw/install/cross-tools/bin/./zip-addr2line'
libtool: install: /usr/bin/install -c addr2line /home/rajjo/zipcpu/sw/install/cross-tools/bin/./zip-addr2line
  /bin/bash ./libtool   --mode=install /usr/bin/install -c readelf '/home/rajjo/zipcpu/sw/install/cross-tools/bin/./zip-readelf'
libtool: install: /usr/bin/install -c readelf /home/rajjo/zipcpu/sw/install/cross-tools/bin/./zip-readelf
  /bin/bash ./libtool   --mode=install /usr/bin/install -c elfedit '/home/rajjo/zipcpu/sw/install/cross-tools/bin/./zip-elfedit'
libtool: install: /usr/bin/install -c elfedit /home/rajjo/zipcpu/sw/install/cross-tools/bin/./zip-elfedit
  /bin/bash ./libtool  --mode=install /usr/bin/install -c nm-new /home/rajjo/zipcpu/sw/install/cross-tools/bin/zip-nm
libtool: install: /usr/bin/install -c nm-new /home/rajjo/zipcpu/sw/install/cross-tools/bin/zip-nm
  /bin/bash ./libtool  --mode=install /usr/bin/install -c strip-new /home/rajjo/zipcpu/sw/install/cross-tools/bin/zip-strip
libtool: install: /usr/bin/install -c strip-new /home/rajjo/zipcpu/sw/install/cross-tools/bin/zip-strip
  /bin/bash ./libtool  --mode=install /usr/bin/install -c cxxfilt /home/rajjo/zipcpu/sw/install/cross-tools/bin/zip-c++filt
libtool: install: /usr/bin/install -c cxxfilt /home/rajjo/zipcpu/sw/install/cross-tools/bin/zip-c++filt
/bin/bash ../../binutils-2.27-zip/binutils/../mkinstalldirs /home/rajjo/zipcpu/sw/install/cross-tools/zip/bin
for i in nm-new strip-new ar ranlib dlltool objdump objcopy readelf; do \
  if [ -f $i ]; then \
    j=`echo $i | sed -e 's/-new//'`; \
    k=`echo $j | sed 's&^&zip-&'`; \
    if [ "/home/rajjo/zipcpu/sw/install/cross-tools/bin/$k" != "/home/rajjo/zipcpu/sw/install/cross-tools/zip/bin/$j" ]; then \
      rm -f /home/rajjo/zipcpu/sw/install/cross-tools/zip/bin/$j; \
      ln /home/rajjo/zipcpu/sw/install/cross-tools/bin/$k /home/rajjo/zipcpu/sw/install/cross-tools/zip/bin/$j >/dev/null 2>/dev/null \
	||  /bin/bash ./libtool --mode=install /usr/bin/install -c $i /home/rajjo/zipcpu/sw/install/cross-tools/zip/bin/$j; \
    fi; \
  else true; \
  fi; \
done
make[7]: Nothing to be done for 'install-data-am'.
make[4]: Nothing to be done for 'install'.
Making install in doc
make[6]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/home/rajjo/zipcpu/sw/install/cross-tools/share/info'
 /usr/bin/install -c -m 644 ../../../binutils-2.27-zip/gas/doc/as.info '/home/rajjo/zipcpu/sw/install/cross-tools/share/info'
 install-info --info-dir='/home/rajjo/zipcpu/sw/install/cross-tools/share/info' '/home/rajjo/zipcpu/sw/install/cross-tools/share/info/as.info'
 /bin/mkdir -p '/home/rajjo/zipcpu/sw/install/cross-tools/share/man/man1'
 /usr/bin/install -c -m 644 '../../../binutils-2.27-zip/gas/doc/as.1' '/home/rajjo/zipcpu/sw/install/cross-tools/share/man/man1/zip-as.1'
Making install in po
make[5]: Nothing to be done for 'install'.
/bin/bash ../../binutils-2.27-zip/gas/../mkinstalldirs /home/rajjo/zipcpu/sw/install/cross-tools/bin
  /bin/bash ./libtool  --mode=install /usr/bin/install -c as-new /home/rajjo/zipcpu/sw/install/cross-tools/bin/zip-as
libtool: install: /usr/bin/install -c as-new /home/rajjo/zipcpu/sw/install/cross-tools/bin/zip-as
/bin/bash ../../binutils-2.27-zip/gas/../mkinstalldirs /home/rajjo/zipcpu/sw/install/cross-tools/zip/bin
n=`echo as | sed 's&^&zip-&'`; \
if [ "/home/rajjo/zipcpu/sw/install/cross-tools/bin/$n" != "/home/rajjo/zipcpu/sw/install/cross-tools/zip/bin/as" ]; then \
  rm -f /home/rajjo/zipcpu/sw/install/cross-tools/zip/bin/as; \
  ln /home/rajjo/zipcpu/sw/install/cross-tools/bin/$n /home/rajjo/zipcpu/sw/install/cross-tools/zip/bin/as >/dev/null 2>/dev/null \
    ||  /bin/bash ./libtool --mode=install /usr/bin/install -c as-new /home/rajjo/zipcpu/sw/install/cross-tools/zip/bin/as; \
else \
  true ; \
fi
make[6]: Nothing to be done for 'install-data-am'.
make[4]: Nothing to be done for 'install'.
make  install-recursive
Making install in po
make[6]: Nothing to be done for 'install'.
 /bin/mkdir -p '/home/rajjo/zipcpu/sw/install/cross-tools/bin'
  /bin/bash ./libtool   --mode=install /usr/bin/install -c ld-new '/home/rajjo/zipcpu/sw/install/cross-tools/bin/./zip-ld.bfd'
libtool: install: /usr/bin/install -c ld-new /home/rajjo/zipcpu/sw/install/cross-tools/bin/./zip-ld.bfd
/bin/bash ../../binutils-2.27-zip/ld/../mkinstalldirs /home/rajjo/zipcpu/sw/install/cross-tools/zip/bin
n=`echo ld.bfd | sed 's/^ld-new$/ld.bfd/;s&^&zip-&'`; \
if test "/home/rajjo/zipcpu/sw/install/cross-tools/bin" != "/home/rajjo/zipcpu/sw/install/cross-tools/zip/bin"; then \
  rm -f /home/rajjo/zipcpu/sw/install/cross-tools/zip/bin/ld.bfd; \
  ln /home/rajjo/zipcpu/sw/install/cross-tools/bin/$n /home/rajjo/zipcpu/sw/install/cross-tools/zip/bin/ld.bfd >/dev/null 2>/dev/null \
  ||  /bin/bash ./libtool --mode=install /usr/bin/install -c ld-new /home/rajjo/zipcpu/sw/install/cross-tools/zip/bin/ld.bfd; \
fi; \
if test "xyes" = "xyes"; then \
  ld=`echo ld | sed 's/^ld-new$/ld.bfd/;s&^&zip-&'`; \
  rm -f /home/rajjo/zipcpu/sw/install/cross-tools/bin/$ld; \
  ln /home/rajjo/zipcpu/sw/install/cross-tools/bin/$n /home/rajjo/zipcpu/sw/install/cross-tools/bin/$ld >/dev/null 2>/dev/null \
  ||  /bin/bash ./libtool --mode=install /usr/bin/install -c ld-new /home/rajjo/zipcpu/sw/install/cross-tools/bin/$ld; \
  if test "/home/rajjo/zipcpu/sw/install/cross-tools/bin" != "/home/rajjo/zipcpu/sw/install/cross-tools/zip/bin"; then \
    rm -f /home/rajjo/zipcpu/sw/install/cross-tools/zip/bin/ld; \
    ln /home/rajjo/zipcpu/sw/install/cross-tools/bin/$n /home/rajjo/zipcpu/sw/install/cross-tools/zip/bin/ld >/dev/null 2>/dev/null \
    ||  /bin/bash ./libtool --mode=install /usr/bin/install -c ld-new /home/rajjo/zipcpu/sw/install/cross-tools/zip/bin/ld; \
  fi; \
fi
/bin/bash ../../binutils-2.27-zip/ld/../mkinstalldirs /home/rajjo/zipcpu/sw/install/cross-tools/zip/lib/ldscripts
for f in ldscripts/* ; do \
  /usr/bin/install -c -m 644 $f /home/rajjo/zipcpu/sw/install/cross-tools/zip/lib/$f ; \
done
 /bin/mkdir -p '/home/rajjo/zipcpu/sw/install/cross-tools/share/info'
 /usr/bin/install -c -m 644 ../../binutils-2.27-zip/ld/ld.info '/home/rajjo/zipcpu/sw/install/cross-tools/share/info'
 install-info --info-dir='/home/rajjo/zipcpu/sw/install/cross-tools/share/info' '/home/rajjo/zipcpu/sw/install/cross-tools/share/info/ld.info'
 /bin/mkdir -p '/home/rajjo/zipcpu/sw/install/cross-tools/share/man/man1'
 /usr/bin/install -c -m 644 '../../binutils-2.27-zip/ld/ld.1' '/home/rajjo/zipcpu/sw/install/cross-tools/share/man/man1/zip-ld.1'
make[5]: Nothing to be done for 'all'.
if test -n ""; then \
	/bin/bash ../../binutils-2.27-zip/libiberty/../mkinstalldirs /home/rajjo/zipcpu/sw/install/cross-tools/lib/`gcc -g -O2 -print-multi-os-directory`; \
	/usr/bin/install -c -m 644 ./libiberty.a /home/rajjo/zipcpu/sw/install/cross-tools/lib/`gcc -g -O2 -print-multi-os-directory`/./libiberty.an; \
	( cd /home/rajjo/zipcpu/sw/install/cross-tools/lib/`gcc -g -O2 -print-multi-os-directory` ; chmod 644 ./libiberty.an ;ranlib ./libiberty.an ); \
	mv -f /home/rajjo/zipcpu/sw/install/cross-tools/lib/`gcc -g -O2 -print-multi-os-directory`/./libiberty.an /home/rajjo/zipcpu/sw/install/cross-tools/lib/`gcc -g -O2 -print-multi-os-directory`/./libiberty.a; \
	case "" in \
	  /*)    thd=;; \
	  *)     thd=/home/rajjo/zipcpu/sw/install/cross-tools/include/;; \
	esac; \
	/bin/bash ../../binutils-2.27-zip/libiberty/../mkinstalldirs ${thd}; \
	for h in ../../binutils-2.27-zip/libiberty/../include/ansidecl.h ../../binutils-2.27-zip/libiberty/../include/demangle.h ../../binutils-2.27-zip/libiberty/../include/dyn-string.h ../../binutils-2.27-zip/libiberty/../include/fibheap.h ../../binutils-2.27-zip/libiberty/../include/floatformat.h ../../binutils-2.27-zip/libiberty/../include/hashtab.h ../../binutils-2.27-zip/libiberty/../include/libiberty.h ../../binutils-2.27-zip/libiberty/../include/objalloc.h ../../binutils-2.27-zip/libiberty/../include/partition.h ../../binutils-2.27-zip/libiberty/../include/safe-ctype.h ../../binutils-2.27-zip/libiberty/../include/sort.h ../../binutils-2.27-zip/libiberty/../include/splay-tree.h ../../binutils-2.27-zip/libiberty/../include/timeval-utils.h; do \
	  /usr/bin/install -c -m 644 $h ${thd}; \
	done; \
fi
make[5]: Nothing to be done for 'install'.
make[3]: Nothing to be done for 'install-target'.
cp ../bench/zipsim.ld install/cross-tools/zip/lib/ldscripts
bash -c "if [[ ! -f build-gas/install-nonce.txt ]]; then touch build-gas/install-nonce.txt; fi"
Binutils installed
make --no-print-directory --directory=build-gcc all-host
make[2]: *** No rule to make target 'all-host'.  Stop.
Makefile:180: recipe for target 'gcc-host' failed
make[1]: *** [gcc-host] Error 2
Makefile:75: recipe for target 'sw' failed
make: *** [sw] Error 2

**Comment by rohitkverma1998** [comment]
I have installed all the dependencies and followed the steps given here.
http://zipcpu.com/zipcpu/2018/01/31/cpu-build.html

Please help to resolve this problem.

**Comment by ZipCPU** [comment]
It looks like your build failed while trying to create the sw/build-gcc directory.  Try removing that directory and starting the build in sw over again.

**Comment by ZipCPU** [comment]
Did this fix your issue at all?

**Comment by rohitkverma1998** [comment]
Yes Sir, Thanks a lot.

**Comment by ZipCPU** [comment]
Awesome!  Thanks for the feedback!
