### ISSUE TITLE
makeinfo: not found

### ISSUE THREAD

**Issue by MJoergen** [ZipCPU/zipcpu#14]
I clone the repo, and follow the instructions in http://zipcpu.com/zipcpu/2018/01/31/cpu-build.html. Essentially, I install all the prerequisites and type `make`.

The build stops with the error:
```
zipcpu/sw/binutils-2.27-zip/missing: 81: makeinfo: not found
```

I'm running on Linux Mint 19.3 (an Ubuntu variant).

The solution I used was to:
```
sudo apt install texinfo
```

**Comment by ZipCPU** [comment]
Are you suggesting I should add texinfo to the list of required dependencies?  I should be able to do that without much hassle.

Dan

**Comment by ZipCPU** [comment]
Are you suggesting I should add texinfo to the list of required dependencies?  I should be able to do that without much hassle.

Dan

**Comment by MJoergen** [comment]
Yes, I think that would be a good idea. For some configurations it may not be necessary, but it caught me by surprise, and adding it to the required dependencies would be helpful to new users.

**Comment by shashidhar1202** [comment]
"sudo apt install texinfo" is missing in the required dependencies section, requesting @ZipCPU  to update

**Comment by GreenMan-1** [comment]
"sudo apt install texinfo" is missing in the required dependencies section, requesting @ZipCPU to update

**Comment by ZipCPU** [comment]
I've updated the dependencies to make this dependency more noticeable.  Please check the INSTALL.md instructions, and see if the notice there would now be sufficient for you.

**Comment by GreenMan-1** [comment]
Thank you it's updated in INSTALL.md , if possible can you please also update in the blog "https://zipcpu.com/zipcpu/2018/01/31/cpu-build.html"

**Comment by ZipCPU** [comment]
Should be fixed now.  Thank you!

Dan
