### ISSUE TITLE
zbasic errors

### ISSUE THREAD

**Issue by kendallgreen** [ZipCPU/zipcpu#17]
On Ubuntu 20.04 LTS with Ryzen 1600, 8GB ram, with $PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/ken/zipcpu/sw/install/cross-tools/bin

git clone https://github.com/ZipCPU/zbasic
cd zbasic
make

After cloning zbasic, I got the following errors running make
ar --transform s,^,`date +%Y%m%d`-zbasic/, -chjf `date +%Y%m%d`-zbasic.tjz  `find sw -name "*.cpp"` `find sw -name "*.c"` `find sw -name "*.h"` `find sw -name "*.sh"` `find sw -name "*.py"`   `find sw -name "*.pl"` `find sw -name "*.png"`  `find sw -name Makefile` `find rtl -name "*.v"` `find rtl -name Makefile` `find sim -name Makefile` `find sim -name "*.cpp"` `find sim -name "*.h"` `find sim -name "*.c"` `find . -name "*.txt"` `find . -name "*.html"`   `find . -name "*.xdc"` `find auto-data -name "*.txt"` README.md
verilator -Wall -Wno-TIMESCALEMOD --MMD -O3 --trace -Mdir ./obj_dir -y wbuart -y wbubus -y cpu -y rtc -y sdspi -cc main.v
%Error: Unknown warning specified: -Wno-TIMESCALEMOD
make[1]: *** [Makefile:77: obj_dir/Vmain.h] Error 1
make: *** [Makefile:140: verilated] Error 2

**Comment by ZipCPU** [comment]
This appears to be a Verilator version issue.  At one point I had to add `-Wno-TIMESCALEMOD` to get ZBasic to build with Verilator and `-Wall`.  It seems as though prior versions of Verilator didn't support this check, but future versions wouldn't pass the design without it.  For now, just remove `-Wno-TIMESCALEMOD` from [the rtl/Makefile](https://github.com/ZipCPU/zbasic/blob/1bf4903bffea500c896bb60daac7e61b49003d5d/rtl/Makefile#L53) and run make again.

I'm open to suggestions of how to deal with this in the future.

Dan
