### ISSUE TITLE
Unknown type name bool error

### ISSUE THREAD

**Issue by Gami-i** [ZipCPU/zipcpu#18]
I am following the tutorial http://zipcpu.com/zipcpu/2018/01/31/cpu-build.html .
When doing the make inside the zipcpu directory, make returns with errors as below.

gcc-10.3.0-zip/gcc/config/zip/genzipops.c:134:47: error: unknown type name ‘bool’
  134 |   const char *rtx_cond, const char *zip_cond, bool offset=false) {
      |                                               ^~~~
gcc-10.3.0-zip/gcc/config/zip/genzipops.c: In function ‘genzipop_long’:
gcc-10.3.0-zip/gcc/config/zip/genzipops.c:302:2: warning: implicit declaration of function ‘genzip_condop’ [-Wimplicit-function-declaration]
  302 |  genzip_condop(fp, md_opname, insn_rtx, insn_cond, zip_op, "eq", "Z");
      |  ^~~~~~~~~~~~~
gcc-10.3.0-zip/gcc/config/zip/genzipops.c: In function ‘genzipop_long_offset’:
gcc-10.3.0-zip/gcc/config/zip/genzipops.c:365:71: error: ‘true’ undeclared (first use in this function)
  365 |  genzip_condop(fp, md_opname, insn_rtx, insn_cond, zip_op, "eq", "Z", true);
      |                                                                       ^~~~
gcc-10.3.0-zip/gcc/config/zip/genzipops.c:365:71: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [Makefile:190: genzipops] Error 1
make: *** [Makefile:81: sw] Error 2

Any suggestions on how to correct this?

**Comment by ZipCPU** [comment]
Fixed.  Check out a new version.  The issue is in the genzipops.c program.  At one time, during testing, I started compiling it with g++ rather than gcc.  g++ has no problems with bool values.  The fix has existed for a while, just in another branch.  I ported the fix to the master branch today and verified that things still build properly.

Dan
