### ISSUE TITLE
wrong comment

### ISSUE THREAD

**Issue by IvanVnucec** [ZipCPU/zipcpu#19]
Here below:  
https://github.com/ZipCPU/zipcpu/blob/548a0efbe5729279f2ae9779a2af4229e8241e52/sw/gas-zippatch.patch#L169

**Comment by ZipCPU** [comment]
Thank you.  Yes, it does look like that comment is a bit out of date.  The ZipCPU was originally a 32-bits per byte machine.  Back when each address referenced 32-bits, a 32-bit address essentially accessed 2^34 octets of data. It now only has 8-bits per byte, so the comment "There's 32 bits per byte" in the line following is also out of date.

Dan

**Comment by IvanVnucec** [comment]
thank you for an explanation. god bless

**Comment by ZipCPU** [comment]
This has now been fixed in [#43a0cdb](https://github.com/ZipCPU/zipcpu/commit/43a0cdbbb549d360aa05b606305667d3c24bad7c).

Dan
