### ISSUE TITLE
make installation error "class Vzipsystem’... has no member named"

### ISSUE THREAD

**Issue by nigel** [ZipCPU/zipcpu#26]
I'm following [this](https://zipcpu.com/zipcpu/2018/01/31/cpu-build.html) tutorial to build ZipCPU. After installing Verilator from source and the dependencies to build this project, I'm getting an error while building `zipcpu_tb.cpp`.

Verilator version: `Verilator 5.002 2022-10-29 rev v5.002-29-gdb39d70c7`

The last couple lines that show the error message are attached.
[error.txt](https://github.com/ZipCPU/zipcpu/files/10117923/error.txt)

**Comment by ZipCPU** [comment]
Which version of Verilator are you using?

**Comment by nigel** [comment]
`Verilator 5.001 devel rev v4.228-125-g56ac054fb`

**Comment by ZipCPU** [comment]
Thank you, sorry I missed that at first.

Let me dig into that a bit, and see if I can get that support back up and running.

Dan

**Comment by ZipCPU** [comment]
Please check out the latest update.  I managed to duplicate your errors, and verified that it now works again.

Also, be advised, this method of simulating the CPU will soon be deprecated with the next release.  I just couldn't test enough configurations using this approach.  Still, it's worth trying out if you are interested in seeing how it works.

Dan

**Comment by nigel** [comment]
Thank you for your time, it works now!

**Comment by odenj** [comment]
I am also facing the same issue. Could you please help me in resolving the issue?

**Comment by ZipCPU** [comment]
I just downloaded and built Verilator from source here and did not see any issues.
