### ISSUE TITLE
Issue in setting up toolchain

### ISSUE THREAD

**Issue by gagana-05** [ZipCPU/zipcpu#27]
![image](https://user-images.githubusercontent.com/82756709/207052040-0f475014-254c-4b49-adf8-6b6c92e4ceee.png)
I am trying to follow your blog on [ZipCpu Toolchain and initial test](https://zipcpu.com/zipcpu/2018/01/31/cpu-build.html) and I am not sure if the path is configured properly, can you please help me with this?

**Comment by ZipCPU** [comment]
It doesn't look like you built and installed the toolchain.  zip-cpp should be in your path if you have done so.

Check out the sw/install/cross-tools/bin directory, and look for zip-cpp.  Is it there?  If so, it's not in your path.  If not, then you need to go into the sw/ directory and type make.

Dan

**Comment by gagana-05** [comment]
Thank you so much, Sir
 I was able to resolve this issue

**Comment by ZipCPU** [comment]
Awesome!
