### ISSUE TITLE
Does sim/verilator/zipsys_tb implement NOUT/SOUT and friend?

### ISSUE THREAD

**Issue by DoctorWkt** [ZipCPU/zipcpu#3]
Hi Dan, in your [latest blog article](http://zipcpu.com/zipcpu/2018/01/01/zipcpu-isa.html) you mention the **NOOP** and **SIM** instructions, and indicate that **NOUT** and **SOUT** can be used to send values to the simulation terminal. I've tried both of these instructions in _sim/verilator/zipsys_tb_ but they don't seem to work. Is this an omission or am I doing something wrong? In particular, I want to be able to do some assembly programming with simple text output using `zipsys_tb -a`. Thanks! Warren

**Comment by ZipCPU** [comment]
Yes, not putting that capability into sim/verilator/zipsys_tb was an oversight.  It has been added into the dev branch.  "make test" now returns a string created by using NOUT instructions.  (Assuming simtest has been built in bench/asm)

Dan
