### ISSUE TITLE
Error with rtl/core/zipwb.v

### ISSUE THREAD

**Issue by bigdot123456** [ZipCPU/zipcpu#33]
When we directly compile the rtl file, it comes with the following error:

Building rtl for Verilator
verilator -Wall -MMD --trace  -cc -y core -y peripherals -y ex -y zipdma -GOPT_PIPELINED=1\\\'b0 -GOPT_LGICACHE=0 -GOPT_LGDCACHE=0 -GOPT_MPY=0 -GOPT_DIV=1\\\'b0 -GOPT_SHIFTS=1\\\'b0 -GOPT_LOCK=1\\\'b0 -GOPT_EARLY_BRANCHING=1\\\'b0 -GOPT_LOWPOWER=1\\\'b0 -GOPT_DISTRIBUTED_REGS=1\\\'b0 -GOPT_USERMODE=1\\\'b0 -GOPT_CIS=1\\\'b0 --prefix Vbonesasm -cc zipbones.v
%Error-PINNOTFOUND: core/zipwb.v:396:5: Parameter pin not found: 'DATA_WIDTH'
  396 |    .DATA_WIDTH(BUS_WIDTH),
      |     ^~~~~~~~~~
                    zipbones.v:638:1: ... note: In file included from zipbones.v
                    ... For error description see https://verilator.org/warn/PINNOTFOUND?v=5.015
%Error: Exiting due to 1 error(s)

![image](https://github.com/ZipCPU/zipcpu/assets/10105303/b5fdd8c8-821a-45a9-99fa-583771f77cc6)

You should correct the parameters DATA_WITH with BUS_WIDTH!

![1711076399426](https://github.com/ZipCPU/zipcpu/assets/10105303/03f980d0-1b19-4493-9349-62d41a8036d6)

**Comment by ZipCPU** [comment]
I'm showing that bug fixed about two months ago.  Please make a new pull and try again.
