### ISSUE TITLE
Line "assign	M_INSN_AWVALID = 0;" is repeated in zipaxil.v

### ISSUE THREAD

**Issue by bman12three4** [ZipCPU/zipcpu#34]
https://github.com/ZipCPU/zipcpu/blob/47e2c291bd33fa8ce419ebac109ad3d65b7fefee/rtl/zipaxil.v#L972-L973

This assign statement is repeated causing a multiple assignment error.

**Comment by ZipCPU** [comment]
Resolved.  Thank you for the pull request.

Dan
