### ISSUE TITLE
Compatibility issue with Cygwin

### ISSUE THREAD

**Issue by MBagheriAstro** [ZipCPU/zipcpu#4]
Hello,
I am trying to unzip and make the zipcpu folder in Windows 10 using Cygwin, but since you are not allowed to create any folder with name "aux" in windows, there is no way I can extract this code completely. Is there any chance you can rename this folder to something else? It is inside the rtl folder.

Thanks,
Mahdi

**Comment by ZipCPU** [comment]
Really??  Ok, sure, that wasn't a bug I was expecting, but there's no reason the folder needs to be named "aux".  I've just moved it to "ex".  Let me know if that doesn't fix your issue.

**Comment by MBagheriAstro** [comment]
Thanks a lot. It seems to be working now.
