### ISSUE TITLE
Undeclared declarations in dcache.v

### ISSUE THREAD

**Issue by tivervac** [ZipCPU/zipcpu#6]
`r_wb_cyc_gbl`, `r_wb_cyc_lcl`, `lock_gbl`, `lock_lcl` are undefined in zipcpu/dcache.v

**Comment by ZipCPU** [comment]
dcache.v is currently ... under-development.  Therefore, it has many more problems than just those few--the logic doesn't work (yet) at all.  It is unused by the rest of the repo, and so it isn't hurting anything.  I can remove it if it is a problem.

Dan
