### ISSUE TITLE
dependency on build of tools

### ISSUE THREAD

**Issue by blacktigersoftware** [ZipCPU/zipcpu#7]
also needed texinfo package on my Ubuntu 18.04:  sudo apt install texinfo
p.s.  Building so far okay on Windows 10 running the Ubuntu 18.04 Linux subsystem.

**Comment by ZipCPU** [comment]
Thanks for the update!  I was struggling to get it to build on my Ubuntu 18.04 for a bit, but now it seems to build without a problem.

Looking over the INSTALL.md notes, I have texinfo listed as a required dependency.  Did you miss this?

**Comment by blacktigersoftware** [comment]
Short answer - yes I did miss the list in INSTALL.md.  Long answer, I was following instructions from elsewhere --- I think your blog.  I've been struggling to get the ZipCPU to run on something.  

Could I message you?

**Comment by ZipCPU** [comment]
Send me an e-mail, at zipcpu@gmail.com.
