### ISSUE TITLE
zip-gcc returns error when compiling functions that return 8 or 16 bit values

### ISSUE THREAD

**Issue by jope12** [ZipCPU/zipcpu#9]
zip-gcc returns an "internal compiler error" when compiling without optimization and the 
source file contains a function that returns an 8 or 16 bit value (char, short, etc.).
For example a source file test.c:

char func(void)
{
  return 0;
}

Compiled as "zip-gcc -c test.c", it will return the following error:

test.c: In function 'func':
test.c:3:10: internal compiler error: in emit_move_insn, at expr.c:3546
   return 0;
          ^
0x737743 emit_move_insn(rtx_def*, rtx_def*)
	../../gcc-6.2.0-zip/gcc/expr.c:3545
0x6365fe expand_value_return
	../../gcc-6.2.0-zip/gcc/cfgexpand.c:3377
0x640968 expand_return
	../../gcc-6.2.0-zip/gcc/cfgexpand.c:3515
0x640968 expand_gimple_stmt_1
	../../gcc-6.2.0-zip/gcc/cfgexpand.c:3597
0x640968 expand_gimple_stmt
	../../gcc-6.2.0-zip/gcc/cfgexpand.c:3724
0x641de2 expand_gimple_basic_block
	../../gcc-6.2.0-zip/gcc/cfgexpand.c:5730
0x647647 execute
	../../gcc-6.2.0-zip/gcc/cfgexpand.c:6345

Cheers,
Jochen

**Comment by ZipCPU** [comment]
Confirmed.

Looking into it,

Dan

**Comment by ZipCPU** [comment]
Should be fixed in [this patch](https://github.com/ZipCPU/zipcpu/commit/7738187981750e262fe1a38b36990e3d8be5c6c2).

Dan
